language: python
env:
  global:
  - PYTHON_VERSION=$PYTHON_VERSION
  - NUMPY_VERSION=stable
  - MAIN_CMD='python setup.py'
  - CONDA_DEPENDENCIES='six coveralls coverage mock'
  - PIP_DEPENDENCIES=''
  - SETUP_XVFB=False
  - EVENT_TYPE='push pull_request'
  - SETUP_CMD='test'
  - CONDA_CHANNELS='conda-forge'
matrix:
  include:
  - env: PYTHON_VERSION=2.7
    os: linux
  - env: PYTHON_VERSION=2.7
    os: osx
    language: generic
  - env: PYTHON_VERSION=3.6
    os: linux
  - env: PYTHON_VERSION=3.6
    os: osx
    language: generic
install:
- git clone --depth 1 git://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda.sh
script:
- coverage run --source=trollsift setup.py test
after_success:
- if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then coveralls; fi
deploy:
  - provider: pypi
    user: dhoese
    password:
      secure: OZ5xq8R4zSo4m1luNUmo2q2jriu5cmSjrRp/2OKyKmuB09SjO4/jxEIzPP6hfgqV5h/m/3uOtYpLXQBeMf0xX0EZqmsOL0BaRQfDNuaxoVEoGBPC/04Zh6567sjDv615awHw6QTIE0Yw891dy3pun+E1yX1zKtQ9hcDKQ3ZFImg=
    distributions: sdist bdist_wheel
    skip_existing: true
    on:
      tags: true
      repo: pytroll/trollsift
